# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: AzureFileCopy@3
  inputs:
    SourcePath: 'default'
    azureSubscription: 'DCD-CFTAPPS-SBOX'
    Destination: 'AzureBlob'
    storage: 'stdefaultshuttersbox'
    ContainerName: '$web'